apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appid-liberty-deployment
  namespace: default # <-- edit here when using a different namespace in cluster
spec:
  replicas: 1
  template:
    metadata:
      name: appid-liberty-deployment
      labels:
        run: appid-liberty-deployment
    spec:
      containers:
        - name: appid-liberty-deployment
          image: "<REGISTRY_DOMAIN>/<REPOSITORY_NAMESPACE>/appid-liberty:<APP_VERSION>" # <-- edit here
          imagePullPolicy: Always
          env:
            - name: APPID_SERVICE_BINDING
              valueFrom:
                secretKeyRef:
                  name: binding-<APP_ID_INSTANCE_NAME> # <-- edit here
                  key: binding
---
apiVersion: v1
kind: Service
metadata:
  namespace: default # <-- edit here when using a different namespace in cluster
  name: appid-liberty-service-http
  labels:
    run: appid-liberty-deployment
spec:
  type: NodePort
  selector:
    run: appid-liberty-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default # <-- edit here when using a different namespace in cluster
  name: appid-liberty-service-https
  labels:
    run: appid-liberty-deployment
spec:
  type: NodePort
  selector:
    run: appid-liberty-deployment
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443
      nodePort: 30081